version: '2'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: XX34!dfd%sd^&
      MYSQL_DATABASE: todo_app
      MYSQL_USER: web_user
      MYSQL_PASSWORD: password

  nginx:
    image: brianmorgan/nginx:latest
    depends_on:
      - web
    environment:
      HTTP_UPSTREAM_HOST: http://web
      HTTP_UPSTREAM_PORT: 5000
    links:
      - web
    ports:
      - "80:80"

  web:
    image: brianmorgan/flask-uwsgi:latest
    depends_on:
      - db
    environment:
      UWSGI_HTTP_PORT: 5000
      UWSGI_PY_AUTO_RELOAD: 1
      FLASK_APP: app.py
      MYSQL_DATABASE: todo_app
      MYSQL_USER: web_user
      MYSQL_PASSWORD: password
    ports:
      - "8080:5000"
    restart: always
    volumes:
      - ../../flask-todo:/var/code
